# Generated by Django 3.1.1 on 2020-10-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(auto_created=True, upload_to=''),
        ),
    ]
