# Generated by Django 3.1.1 on 2020-10-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201005_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='fathers_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='pan_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='pan_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='paninfo',
            name='scanned_signature',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
